### ISSUE TITLE
Implementation for `yank` (`C-y`)

### ISSUE THREAD

**Issue by williamboman** [linty-org/readline.nvim#2]
I might've developed bad habits, but I find yanking to be a pretty helpful tool to effectively undo deletions. I'm honestly not too sure exactly how `yank` is designed to deal with undo sequences (what I mean by this is say I `<C-w>` two words, yank would restore both words).

**Comment by andmis** [comment]
After https://github.com/linty-org/readline.nvim/commit/f6125cbd60cba8bfd804f365bf93139c28788b33, the mapping above should work as a temporary workaround in Insert/Command-line mode.

**Comment by andmis** [comment]
By the way, to undo deletions, I use `<C-_>`, which is `undo` by default in normal Readline contexts (Bash, etc.), and in Vim I use the following two mappings, which makes `<C-_>` work as "undo" almost everywhere in a terminal app:
```
  inoremap <C-_> <C-Bslash><C-o>u
  nnoremap <C-_> u
```

**Bonus:** If you do the above, you can remap `⌘Z` or whatever you use for "undo" in your OS to produce `<C-_>` just in your terminal emulator, and then you have an undo key that works consistently everywhere.

**Comment by williamboman** [comment]
> I suppose for your particular use case, you are fine with this, right?

I believe so yes!

> For now, you could try the following, which will yank the most-recently-killed word or line (but won't yank multiple words/lines). (This works because readline.nvim already puts killed content into `"-`, the small-delete register.)

Ah let me try this! From just reading it sounds like exactly what I need.

> By the way, to undo deletions, I use <C-_>, 

_cries in Nordic QWERTY_, I can barely overcome some of the default vim keybinds haha 🥲 

> Bonus: If you do the above, you can remap ⌘Z or whatever you use for "undo" in your OS to produce <C-_> just in your terminal emulator, and then you have an undo key that works consistently everywhere.

Great tip!!

**Comment by williamboman** [comment]
Works great, I'll close this as my use case is solved!

**Comment by williamboman** [comment]
> By the way, to undo deletions, I use `<C-_>`, which is `undo` by default in normal Readline contexts (Bash, etc.), and in Vim I use the following two mappings, which makes `<C-_>` work as "undo" almost everywhere in a terminal app:

Hey again! I'm struggling a bit with getting this to work. It seems like vim's undo stack isn't populated by readline actions (like `readline.backward_kill_word`), so undoing via `<C-_>` binding isn't really working as I'd expect. Or am I missing something 🤔?

**Comment by andmis** [comment]
In my setup the `readline` functions do indeed populate the undo stack.

If you run `:lua require 'readline'.kill_word()` and `:undolist`, the edit doesn't appear?

**Comment by williamboman** [comment]
So this is what happens if enter some text, and then do a backward kill word (`<C-w>`) followed by an undo (`<C-_>`): https://asciinema.org/a/Awuzkz7NVcV9AaeaXCFzUfYdk. What I am thinking is that maybe readline needs to explicitly populate the undo stack (like with `:h i_CTRL-G_u`) when doing a text operation? 

Here are my keymaps:

```lua
vim.keymap.set("!", "<M-f>", readline.forward_word)
vim.keymap.set("!", "<M-b>", readline.backward_word)
vim.keymap.set("!", "<C-a>", readline.beginning_of_line)
vim.keymap.set("!", "<C-e>", readline.end_of_line)
vim.keymap.set("!", "<M-d>", readline.kill_word)
vim.keymap.set("!", "<C-w>", readline.backward_kill_word)
vim.keymap.set("!", "<C-k>", readline.kill_line)
vim.keymap.set("!", "<C-u>", readline.backward_kill_line)
vim.keymap.set("!", "<C-y>", "<C-r>-")
vim.keymap.set("i", "<C-_>", "<C-Bslash><C-o>u")
```

**Comment by andmis** [comment]
@williamboman this should be fixed in https://github.com/linty-org/readline.nvim/commit/1c8873654f7ab640a8ab69dc6aeaee2dffba1c8f, give it a try? Thanks for following up on this, I think this makes a big difference in usability. I had always felt that undo felt really awkward (I also use an Insert-mode undo mapping) and I think this was why.

**Comment by williamboman** [comment]
Yeah seems to work much better, great work!
