### ISSUE TITLE
Troubleshooting the bindings

### ISSUE THREAD

**Issue by farzadmf** [linty-org/readline.nvim#3]
Hey,

First of all, thank you for the plugin. The readline support in command mode is really something I was always missing.

However, I have an issue with `Alt+b` in insert mode and I was wondering if there's something from my own config overriding the plugin's binding or something else.

Is there anyway I can know?

**Comment by andmis** [comment]
Hmm. You can do `:verbose imap <M-b>` to see where the mapping is getting set from. Or try moving your mapping to the end of your `init.lua`. Or add it interactively by doing `:lua vim.keymap.set('i', '<M-b>', require 'readline'.backward_word')`.

But I would guess that if you are using macOS, then it's likely you have not configured your terminal emulator (iTerm2, Terminal.app, kitty, alacritty, etc.) to treat the Option key (⌥) as an alt/meta key. Might this be the problem?

**Comment by farzadmf** [comment]
> Might this be the problem?

I am indeed using a Mac (unfortunately), but I don't think that's the problem because other `Alt` combinations are working fine (I use Alacritty and I have quite a few of those bindings configured in there)

I'll give your other suggestions a try and get back to you 👀

**Comment by farzadmf** [comment]
> You can do `:verbose imap <M-b>`

Thank you for the suggestion, seems like `Alt-b` by default is bound in [auto-pairs](https://github.com/jiangmiao/auto-pairs) that I'm using. I changed this:
```
let g:AutoPairsShortcutBackInsert = '...'
```
And it freed up `Alt-b`, and it can be used by `readline`

Gonna close this because it's resolved as far as I'm concerened.

Thank you for the help
