### ISSUE TITLE
Word separators dont act exactly like in bash's Readline

### ISSUE THREAD

**Issue by CyberMango** [linty-org/readline.nvim#5]
When looking at some readline behaviors regarding word separators in real readline (tested with bash's readline and in [readline.vim](https://github.com/ryvnf/readline.vim)) compared to this plugin, the behavior is different.

Im using these mappings:
```
vim.keymap.set('!', '<c-f>', '<right>')
vim.keymap.set('!', '<c-b>', '<left>')
vim.keymap.set('!', '<m-f>', readline.forward_word)
vim.keymap.set('!', '<m-b>', readline.backward_word)
vim.keymap.set('!', '<c-a>', readline.beginning_of_line)
vim.keymap.set('!', '<c-e>', readline.end_of_line)
vim.keymap.set('!', '<c-d>', '<Delete>')
vim.keymap.set('!', '<c-h>', '<BS>')
vim.keymap.set('!', '<m-d>', readline.kill_word)
vim.keymap.set('!', '<c-w>', readline.backward_kill_word)
vim.keymap.set('!', '<c-k>', readline.kill_line)
vim.keymap.set('!', '<c-u>', readline.backward_kill_line)
vim.keymap.set('c', '<c-j>', '<enter>')
```
when using alt-f (=readline.forward_word), in readline.nvim the cursors skips over "_", for example (with "|" representing the cursor location):
initial state:          `|underscored_word`
using alt-f in bash result:                 `underscored|_word`
using alt-f in readline.nvim result: `underscored_word|`

The behavior is also different for ctrl-w(=readline.backward_kill_word):
initial state: `word slash/separated/word|`
using ctrl-w in bash result:                  `word |`
using ctrl-w in readline.nvim result:    `word slash/separated/|`

Do you intend to keep the current behavior or follow bash's readline behavior?

**Comment by andmis** [comment]
Does this help? https://github.com/linty-org/readline.nvim#configuring-word-characters

Regarding `<C-w>` specifically, Readline actually has two backward-kill-word-like commands, with `<M-BS>` and `<C-w>` being their default shortcuts, see https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html. I would be open to adding `forward_WORD`, `kill_WORD`, etc., which break on whitespace, if that would be useful for you.

I am also open to adding another method of configuring the default set of word characters besides simply overwriting `require 'readline'.word_chars.c` with whatever you prefer.

**Comment by andmis** [comment]
Hmm. Based on [this](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Moving.html), it seems like the word-motion commands are pretty consistent about "words" consisting of letters and digits. So I think I will change the default set of word characters to not include an underscore. Thanks for pointing this out.

Regarding how you would like `<C-w>` to behave, it looks like the Readline commands are called `shell-forward-word`, `shell-kill-word`, etc. I could add `shell_forward_word` and so on to readline.nvim if you would use these functions, LMK.

**Comment by andmis** [comment]
@CyberMango https://github.com/linty-org/readline.nvim/commit/dd315dc7aa3472743d66c60d00521ed1f148f22a

**Comment by CyberMango** [comment]
@andmis My purpose in using this plugin is to have consistent readline shortcuts between bash and nvim, so if you dont mind i would love to have functions such as `shell_forward_word` for this kind of consistency.

**Comment by andmis** [comment]
Sounds good, give it a try after the changes in https://github.com/linty-org/readline.nvim/commit/cf1bd41808332f4ae8fa2d52f4bf006e70a1e8ef (just upgrade to latest `master`) -- it looks like `unix-word-rubout` (the command for `<C-w>`) is what you actually wanted to I went ahead and implemented that. The default behavior with the default bindings should now match `bash`, and I'll (probably) consider it a bug if the behaviors disagree. Thanks again!

**Comment by CyberMango** [comment]
@andmis This works perfectly for me. This can be closed as far as im concerned.
Thanks you.
